[project]
name = "an-cli"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "arguably>=1.3.0",
    "numpy>=2.2.4",
    "rich>=14.0.0",
    "sympy>=1.13.3",
]
